# this name shows up on the GitHub Actions badge
name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14', '16' ]
    name: test on node ${{ matrix.node }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - name: Unit tests
        run: npm run test:unit:once
      - name: API tests
        run: npm run test:api:once
      - name: Coveralls (unit tests)
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    name: publish
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run compile:dist
      - run: cp package.json README.md LICENSE dist/
      - uses: JS-DevTools/npm-publish@v1
        with:
          package: dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
